# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stardust < Formula
  desc "Local-first, git-backed, markdown-truth context engine for AI agents"
  homepage "https://github.com/alxxpersonal/stardust"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alxxpersonal/stardust/releases/download/v0.5.0/stardust_darwin_amd64.tar.gz"
      sha256 "fdf6f985fed6260d7c48109677c277090a6e2de9ce2a953ddb018bd0e9165a7f"

      define_method(:install) do
        bin.install "stardust"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alxxpersonal/stardust/releases/download/v0.5.0/stardust_darwin_arm64.tar.gz"
      sha256 "517e2c99915fa598aee344a86ab4a0a5f33578138f87a7d92a5ba52e3cc78c09"

      define_method(:install) do
        bin.install "stardust"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alxxpersonal/stardust/releases/download/v0.5.0/stardust_linux_amd64.tar.gz"
      sha256 "e6002ea61ef27e6c78519de92aede8711cd3cec9601cf8e9ac5ae3227a7cc019"
      define_method(:install) do
        bin.install "stardust"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alxxpersonal/stardust/releases/download/v0.5.0/stardust_linux_arm64.tar.gz"
      sha256 "d6916c4c13bdf85ec1d68e394d044820438b63bf2b19394fd7f61c0c2a751bc8"
      define_method(:install) do
        bin.install "stardust"
      end
    end
  end

  test do
    system "#{bin}/stardust", "--version"
  end
end
